favicon: /images/webstack_icon_producthunt.png


logo:
  expanded: /images/logo@2x.png
  collapsed: /images/logo-collapsed@2x.png
  dark: /images/logo_dark@2x.png

flag:
  icon: flag-cn
  name: Chinese

search: false

githubCorner: '<a href="https://github.com/RoboPPN/web-nav" class="github-corner" aria-label="View source on GitHub"><svg width="80" height="80" viewBox="0 0 250 250" style="fill:#151513; color:#fff; position: absolute; top: 0; border: 0; right: 0;" aria-hidden="true"><path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path><path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path><path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path></svg></a><style>.github-corner:hover .octo-arm{animation:octocat-wave 560ms ease-in-out}@keyframes octocat-wave{0%,100%{transform:rotate(0)}20%,60%{transform:rotate(-25deg)}40%,80%{transform:rotate(10deg)}}@media (max-width:500px){.github-corner:hover .octo-arm{animation:none}.github-corner .octo-arm{animation:octocat-wave 560ms ease-in-out}}</style>'

menu:
  - name: 我
    icon: far fa-star
    config: My

  - name: 我的朋友
    icon: far fa-star
    config: MyFriends
    
  - name: 学习
    icon: far fa-star
    config: study

  - name: 社区
    icon: far fa-star
    config: Community

  - name: 大佬的博客
    icon: far fa-star
    config: Gangster


  - name: 其他工具
    icon: fas fa-tools
    submenu:
      - name: Emoji大全
        icon: fas fa-tools
        config: Emoji

      - name: 资源下载
        icon: fas fa-star
        config: Downloader

      - name: 资源转换
        icon: fas fa-tools
        config: Transform



My:
  - name: 我的Github
    url: https://github.com/RoboPPN
    # img: /images/logos/myblog.png
    description: 
  - name: 我的CSDN
    url: https://blog.csdn.net/seniorc
    # img: /images/logos/myblog.png
    description: 

MyFriends:
  - name: 甘伟泽
    url: https://gbrain.top/
    # img: /images/logos/myblog.png
    description: 

  - name: 徐玺
    url: https://www.roboxx.ltd/
    # img: /images/logos/myblog.png
    description: 

  - name: 张阳
    url: https://joycekirkland.site/
    # img: /images/logos/myblog.png
    description: 

  - name: 创新哥
    url: https://sinnammanyo.cn/docs/
    # img: /images/logos/myblog.png
    description: 

  - name: 佳佳鸽
    url: https://blog.csdn.net/weixin_43793181
    # img: /images/logos/myblog.png
    description: 骑摩托吗？买摩托吗？

  - name: 伍晁均
    url: https://www.notion.so/Learning-28a0ac3bcc454c3badab2a106eae6125
    # img: /images/logos/myblog.png
    description: 高佬

  - name: 林宇轩
    url: https://wiki-power.com/
    # img: /images/logos/myblog.png
    description: 

  - name: 刘炜荣
    url: https://blog.csdn.net/weixin_49590533?
    # img: /images/logos/myblog.png
    description: 大聪明


study:
  - name: ROS理论与实践课件
    url: http://www.autolabor.com.cn/book/ROSTutorials/
    # img: /images/logos/github.png
    description:

  - name: CSS
    url: https://developer.mozilla.org/en-US/docs/Learn/CSS/
    # img: /images/logos/github.png
    description: 学习ＣＳＳ

  - name: HTML
    url: https://developer.mozilla.org/en-US/docs/Web/HTML/
    # img: /images/logos/github.png
    description: 学习ＨＴＭＬ
  
  - name: Create
    url: https://create-react-app.dev/
    # img: /images/logos/github.png
    description: 　
  
  - name: Autoware教程-创客制造
    url: https://www.ncnynl.com/category/autoware/2/
    # img: /images/logos/github.png
    description: 　

  - name: Autoware文档
    url: https://autoware.readthedocs.io/en/feature-documentation_rtd/index.html
    # img: /images/logos/github.png
    description: 

  - name: C++ template
    url: https://github.com/wuye9036/CppTemplateTutorial#1-template%e7%9a%84%e5%9f%ba%e6%9c%ac%e8%af%ad%e6%b3%95
    # img: /images/logos/github.png
    description: 



Community: 
  - name: 野狼知识库
    url: https://wiki.wildwolf.pw/
    # img: /images/logos/github.png
    description: 

  - name: Docusaurus中文网
    url: https://www.docusaurus.cn/
    # img: /images/logos/github.png
    description: 一款轻便美观的博客框架
  
  - name: 高校人工智能挑战赛
    url: https://www.robomaster.com/zh-CN/robo/icra
    # img: /images/logos/github.png
    description: 
  
  - name: RoboMaster 2019 AI 机器人平台
    url: https://robomaster.github.io/RoboRTS-Tutorial/#/
    # img: /images/logos/github.png
    description: 

  - name: 古月居
    url: https://www.guyuehome.com/
    # img: /images/logos/github.png
    description: 

  

  - name: 创客智造
    url: https://www.ncnynl.com/archives/201708/1880.html
    # img: /images/logos/github.png
    description: 
  
  - name: ROS's Wiki
    url: http://wiki.ros.org/navigation?distro=noetic
    # img: /images/logos/github.png
    description: 
 
  - name: ROS's Answer
    url: http://wiki.ros.org/navigation?distro=noetic
    # img: /images/logos/github.png
    description: ROS提问网站

  
  

Gangster:
  - name: Red Blob Games
    url: https://www.redblobgames.com/
    # img: /images/logos/github.png
    description: 2D寻路算法领域

  - name: 峰华前端工程师
    url: https://zxuqian.cn/
    # img: /images/logos/github.png
    description: 前端大佬

  - name: 大叔的小站
    url: https://imuncle.github.io/
    # img: /images/logos/github.png
    description: ＲＭｅｒ
  - name: 白夜行的狼
    url: https://haoqchen.site/
    # img: /images/logos/github.png
    description: ROS Navigation源码完全详解 
  - name: 不知所云
    url: https://lkevin98.gitee.io/blog/
    # img: /images/logos/github.png
    description: Ubuntu+ROS+QT
  - name: 前站导航
    url: https://www.hifast.cn/
    # img: /images/logos/github.png
    description: 这个网站什么都有

  



Emoji:
  - name: Emoji大全①
    url: https://www.emojiall.com/zh-hans
    # img: /images/logos/github.png
    description: Emoji中文官方网站

  - name: Emoji大全②
    url: http://emojixd.com/
    # img: /images/logos/github.png
    description: Ｅｍｏｊｉ表情大全


Downloader:
  - name: 音乐下载器
    url: http://www.xieqian.vip/music/
    # img: /images/logos/myBlog.png
    description: 一款在线音乐下载器

  - name: bilibili视频下载
    url: https://xbeibeix.com/api/bilibili/
    # img: /images/logos/myBlog.png
    description:

Transform:
  - name: 资源转换器
    url: https://onlineconvertfree.com/zh/convert/
    # img: /images/logos/myBlog.png
    description: 免费转换各种转换何文件、图片、视频、音频和照片转换工具！


since: 2021

busuanzi:
  enable: true
  position: sidebar # 'footer','sidebar'
  pv: 本站总访问量$pv
  uv: 本站总访客数$uv

custom:
  head: |- # 以下内容插入到<head></head>标签内，可设置多行，注意每行开头至少四个空格
    <!-- 直接添加html内容即可 -->
    <!-- 可设置多行 -->
  body: |- # 以下内容插入到</body>标签之前，可设置多行，注意每行开头至少四个空格
    <!-- 直接添加html内容即可 -->
    <!-- 可设置多行 -->

js:
  header: /js/header.js
  footer: /js/footer.js
  jquery: /js/jquery-1.11.1.min.js
  bootstrap: /js/bootstrap.min.js
  TweenMax: /js/TweenMax.min.js
  resizeable: /js/resizeable.min.js
  joinable: /js/joinable.js
  xenonApi: /js/xenon-api.min.js
  xenonToggles: /js/xenon-toggles.min.js
  xenonCustom: /js/xenon-custom.min.js
  lozad: /js/lozad.min.js
  html5shiv: /js/html5shiv.min.js
  respond: /js/respond.min.js
  busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

css:
  hclonely: /css/hclonely.css
  fonts: //fonts.loli.net/css?family=Arimo:400,700,400italic
  linecons: /css/fonts/linecons/css/linecons.min.css
  fontawesome: /css/fonts/fontawesome/css/all.min.css
  bootstrap: /css/bootstrap.min.css
  xenonCore: /css/xenon-core.min.css
  xenonComponents: /css/xenon-components.min.css
  xenonSkins: /css/xenon-skins.min.css
  nav: /css/nav.min.css
